spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/jdbc-practice-db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:admin1234}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true
